package DAO;

import java.sql.SQLException;
import java.util.Optional;

import Model.Account;

public interface AccountDao {

    /**
     * Adds a new account to a database.
     * 
     * @param account The new account to add, which contains a valid username and password.
     * @return The same Account object passed into this method, but with an ID generated by the database.
     * @throws SQLException If there is an issue with the database.
     */
    Account addAccount(Account account) throws SQLException;

    /**
     * Retrieves an account from a database by username.
     * 
     * @param username The username to use to look up an account in the database.
     * @return An Optional containing an Account object or an empty Optional if there is no account with the provided
     *  username in the database.
     * @throws SQLException If there is an issue with the database.
     */
    Optional<Account> getAccount(String username) throws SQLException;

    /**
     * Retrieves an account from a database by using ID.
     * 
     * @param id The ID to use to look up an account in the database.
     * @return An Optional containing an Account object or an empty Optional if there is no account with the provided
     *  ID in the database.
     * @throws SQLException If there is an issue with the database.
     */
    Optional<Account> getAccount(int id) throws SQLException;
}
